### ISSUE TITLE
The request is missing a valid API key. (PERMISSION_DENIED)

### ISSUE THREAD

**Issue by tefracky** [inspiredminds/contao-youtube-sync#1]
Hello,

I tried to use the addon, since it looks very promissing for me. I installed the package via the Contao-Manager and added a file "config/config.yml" in the root directory of the installation and insered the API key as described in the readme:

```
# config/config.yml
contao_youtube_sync:
    developer_key: 'AIza...'
```

 Afterwards, I added a news, insered the Playlist ID, author, target directory and saved it. Afterwards, I tried to sync the videos by clicking on "YouTube sync", the following error appears:

`{ "error": { "code": 403, "message": "The request is missing a valid API key.", "errors": [ { "message": "The request is missing a valid API key.", "domain": "global", "reason": "forbidden" } ], "status": "PERMISSION_DENIED" } } `

I checked the Cloud Api and the YouTube Data API v3 is activated and the API key is not restricted. What is going wrong?

**Comment by fritzmg** [comment]
> and added a file "config/config.yml" in the root directory of the installation and insered the API key as described in the readme:

Did you rebuild the application cache afterwards?

**Comment by tefracky** [comment]
Thanks a lot, it works now!
