### ISSUE TITLE
Contao 5 compability

### ISSUE THREAD

**Issue by tefracky** [inspiredminds/contao-youtube-sync#2]
Hi,

when I want to update to Contao 5, the update is blocked by the YouTube Sync Add-on:

`inspiredminds/contao-youtube-sync 1.0.3 requires contao/news-bundle ^4.9 -> found contao/news-bundle[4.9.0, ..., 4.13.12] but it conflicts with your root composer.json require (^5.0).`

Are there any plans to update the add-on on order to make it usable with Contao 5?

**Comment by fritzmg** [comment]
`1.0.4` is now unlocked for Contao 5.

**Comment by tefracky** [comment]
Well, this was fast, thanks a lot!

**Comment by fritzmg** [comment]
You are welcome 😊 Consider sponsoring if you want 😉 But regardless of sponsorship: our plan is to make all our (not abandoned) extensions compatible with Contao 5. It just takes time and we are currently doing it one-by-one and on demand.
